kind: pipeline
type: docker
name: ci

steps:
  - name: gofmt
    image: golang:1.25-alpine
    commands:
      - gofmt_out="$(gofmt -l ./cmd ./internal)"
      - |
        if [ -n "$gofmt_out" ]; then
          echo "The following files need gofmt:" >&2
          echo "$gofmt_out" >&2
          exit 1
        fi
  - name: gomodtidy
    image: golang:1.25-alpine
    commands:
      - apk add --no-cache git
      - go mod tidy
      - |
        if [ -f go.sum ]; then
          git diff --exit-code go.mod go.sum
        else
          git diff --exit-code go.mod
        fi
  - name: govet
    image: golang:1.25-alpine
    commands:
      - go vet ./...
  - name: gotest-race
    image: golang:1.25
    commands:
      - go test ./... -race
  - name: coverage
    image: golang:1.25-alpine
    commands:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out
  - name: govulncheck
    image: golang:1.25-alpine
    commands:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - export PATH="$PATH:$(go env GOPATH)/bin"
      - govulncheck ./...
